### ISSUE TITLE
Challenge functionality

### ISSUE THREAD

**Issue by Sikian** [Starbow/erosd#17]
Criteria:
- It has to be awesome and flawless.
- A user can left click on a user in the chat to challenge him.
- That user will receive a notification on the challenge.
- If the user accepts, a match will be created between both users.
- If the user rejects, the challenging user will not be able to challenge that user during at least 1 minute.
- The challenging player should be able to cancel his request (really needed? yes, in case of mistake).
- The challenge times out after a minute.

**Comment by XiphiasSB** [comment]
I think 1 min is enough. Like what if someone hots reject by mistake or something? (Oh, I guess then they can switch who challenges who..) anyhow, I think 1 min is enough.
