### ISSUE TITLE
Can not build project

### ISSUE THREAD

**Issue by esiqveland** [Starbow/erosd#7]
Building/Getting fails with:
```
$ go get -u -v github.com/Starbow/erosd
github.com/Starbow/erosd (download)
github.com/ChrisHines/GoSkills (download)
github.com/golang/protobuf (download)
github.com/coopernurse/gorp (download)
github.com/go-sql-driver/mysql (download)
github.com/gorilla/context (download)
github.com/gorilla/mux (download)
github.com/gorilla/websocket (download)
github.com/mattn/go-sqlite3 (download)
github.com/msbranco/goconfig (download)
github.com/Sikian/oauth2 (download)
package github.com/Starbow/erosd
	imports github.com/ChrisHines/GoSkills/skills
	imports github.com/ChrisHines/GoSkills/skills/numerics
	imports github.com/ChrisHines/GoSkills/skills/trueskill
	imports github.com/Sikian/oauth2
	imports github.com/Sikian/oauth2
	imports github.com/Sikian/oauth2: code in directory /Users/eivind/src/gopath/src/github.com/Sikian/oauth2 expects import "golang.org/x/oauth2"
```

**Comment by Veritasimo** [comment]
That oauth fork doesn't use the master branch, so it doesn't play nice with go get. This is one for Sikian to fix. Until then you'll have to clone it in manually.

**Comment by esiqveland** [comment]
Do you mean cloning golang.org/x/oauth2 at a different version (not master HEAD)?

**Comment by Veritasimo** [comment]
Sikian's fork of that repo. There's only one other branch in it, which is the one you want. This happened after I stopped maintaining, so he'd know more about why it's like that, or if we're able to use the main package now. There's a VM in the dev forum with all of this set up already.

**Comment by esiqveland** [comment]
Ah, ok, I see. Where is the forum?

**Comment by Veritasimo** [comment]
Xiphias will know who controls access to it these days

**Comment by Sikian** [comment]
@esiqveland can we close this?

**Comment by esiqveland** [comment]
yes, I left a note about it in the readme.
